name: Deploy US Client

on:
  push:
    branches:
      - dev  # ou `dev`, selon ton cas

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: alexandredelesse/us-ambulance

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Read version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build & Push Docker image
        run: |
          TAG_VERSION="v${VERSION}-prod"
          TAG_LATEST="latest-prod"
          docker build --platform linux/amd64 \
            -t $IMAGE_NAME:$TAG_VERSION \
            -t $IMAGE_NAME:$TAG_LATEST \
            --build-arg ENV_FILE=.env.prod .
          docker push $IMAGE_NAME:$TAG_VERSION
          docker push $IMAGE_NAME:$TAG_LATEST

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            cd /root/app/us-ambulance
            ./redeploy.sh dev latest
